apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlmodelapi
  labels:
    role: mlmodelapi
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mlmodelapi
  template:
    metadata:
      labels:
        role: mlmodelapi
    spec:
      containers:
      - name: mlmodelapi
        image: IMAGEPLACEHOLDER
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m