apiVersion: v1
kind: Service
metadata:
  name: mlmodelapi
  labels:
    role: mlmodelapi
spec:
  selector:
    role: mlmodelapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer